-- ─────────────────────────────────────────────────────────────────────────────
-- 0002_rls — tenant isolation via Postgres Row-Level Security
-- GENERATED by packages/db/scripts/gen-rls.mjs — do not edit by hand.
--
-- Runtime connections use a login role that is a member of arena_app
-- (NOBYPASSRLS). Every request runs inside a transaction that first executes
--   SELECT set_config('app.current_org', '<org uuid>', true);
-- If the setting is missing, app.current_org_id() is NULL and every policy
-- evaluates to NULL → zero rows. The system fails CLOSED.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE SCHEMA IF NOT EXISTS app;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_app') THEN
    CREATE ROLE arena_app NOLOGIN NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_readonly') THEN
    CREATE ROLE arena_readonly NOLOGIN NOBYPASSRLS;
  END IF;
  -- Group role for platform (Super Admin) services. NOTE: BYPASSRLS is not
  -- inherited through membership; the platform *login* role must itself be
  -- created WITH BYPASSRLS by infrastructure (see docs/05-multi-tenancy.md).
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_platform') THEN
    CREATE ROLE arena_platform NOLOGIN;
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION app.current_org_id() RETURNS uuid
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $fn$ SELECT NULLIF(current_setting('app.current_org', true), '')::uuid $fn$;

GRANT USAGE ON SCHEMA public, app TO arena_app, arena_readonly, arena_platform;
GRANT EXECUTE ON FUNCTION app.current_org_id() TO arena_app, arena_readonly, arena_platform;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO arena_app, arena_platform;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO arena_readonly;
REVOKE ALL ON "_prisma_migrations" FROM arena_app, arena_readonly;
-- Tables created by later migrations (run as the owner) get the same grants.
-- They still need their own RLS policy: the static tenancy test enforces it.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO arena_app, arena_platform;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO arena_readonly;

-- Platform reference data & catalogs: tenants read, never write.
REVOKE INSERT, UPDATE, DELETE ON "Country", "Currency", "SubscriptionPlan", "PlanFeature",
  "ClientRelease", "Permission", "PlatformRoleAssignment" FROM arena_app;
-- Tenant rows managed by the platform (billing, feature flags, impersonation).
REVOKE INSERT, UPDATE, DELETE ON "Subscription", "SubscriptionInvoice", "OrganizationFeature", "ImpersonationSession" FROM arena_app;
-- Tenants never create or delete organizations.
REVOKE INSERT, DELETE ON "Organization" FROM arena_app;


-- Achievement
ALTER TABLE "Achievement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Achievement" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Achievement" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Alert
ALTER TABLE "Alert" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Alert" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Alert" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ApiKey
ALTER TABLE "ApiKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiKey" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ApiKey" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- AuditLog
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "AuditLog" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Bill
ALTER TABLE "Bill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Bill" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Bill" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Booking
ALTER TABLE "Booking" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Booking" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- BookingResource
ALTER TABLE "BookingResource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BookingResource" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "BookingResource" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Branch
ALTER TABLE "Branch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Branch" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Branch" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Brand
ALTER TABLE "Brand" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Brand" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Brand" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Campaign
ALTER TABLE "Campaign" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Campaign" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Campaign" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CashDrawer
ALTER TABLE "CashDrawer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CashDrawer" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CashDrawer" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CashMovement
ALTER TABLE "CashMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CashMovement" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CashMovement" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ComboItem
ALTER TABLE "ComboItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ComboItem" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ComboItem" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Customer
ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Customer" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CustomerAchievement
ALTER TABLE "CustomerAchievement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerAchievement" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CustomerAchievement" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CustomerFavoriteGame
ALTER TABLE "CustomerFavoriteGame" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerFavoriteGame" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CustomerFavoriteGame" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CustomerRestriction
ALTER TABLE "CustomerRestriction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerRestriction" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CustomerRestriction" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CustomerSegment
ALTER TABLE "CustomerSegment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerSegment" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CustomerSegment" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CustomerSegmentMember
ALTER TABLE "CustomerSegmentMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerSegmentMember" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CustomerSegmentMember" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- CustomerSession
ALTER TABLE "CustomerSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CustomerSession" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "CustomerSession" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Device
ALTER TABLE "Device" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Device" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Device" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DeviceAccessory
ALTER TABLE "DeviceAccessory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceAccessory" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DeviceAccessory" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DeviceBootInfo
ALTER TABLE "DeviceBootInfo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceBootInfo" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DeviceBootInfo" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DeviceCommand
ALTER TABLE "DeviceCommand" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceCommand" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DeviceCommand" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DeviceCredential
ALTER TABLE "DeviceCredential" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceCredential" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DeviceCredential" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DeviceEnrollmentToken
ALTER TABLE "DeviceEnrollmentToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceEnrollmentToken" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DeviceEnrollmentToken" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DeviceHardware
ALTER TABLE "DeviceHardware" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceHardware" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DeviceHardware" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DeviceHeartbeat
ALTER TABLE "DeviceHeartbeat" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeviceHeartbeat" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DeviceHeartbeat" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- DisklessIntegration
ALTER TABLE "DisklessIntegration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DisklessIntegration" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "DisklessIntegration" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- EdgeNode
ALTER TABLE "EdgeNode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EdgeNode" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "EdgeNode" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Employee
ALTER TABLE "Employee" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Employee" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Employee" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- EmployeeRoleAssignment
ALTER TABLE "EmployeeRoleAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmployeeRoleAssignment" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "EmployeeRoleAssignment" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Expense
ALTER TABLE "Expense" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Expense" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Expense" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Game
ALTER TABLE "Game" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Game" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Game" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());
CREATE POLICY shared_catalog_read ON "Game" FOR SELECT USING ("organizationId" IS NULL);

-- GameInstallation
ALTER TABLE "GameInstallation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameInstallation" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "GameInstallation" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- GameLicense
ALTER TABLE "GameLicense" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameLicense" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "GameLicense" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- GameUpdateJob
ALTER TABLE "GameUpdateJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GameUpdateJob" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "GameUpdateJob" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- GamingSession
ALTER TABLE "GamingSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GamingSession" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "GamingSession" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- IdempotencyRecord
ALTER TABLE "IdempotencyRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IdempotencyRecord" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "IdempotencyRecord" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ImpersonationSession
ALTER TABLE "ImpersonationSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImpersonationSession" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ImpersonationSession" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- InventoryItem
ALTER TABLE "InventoryItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InventoryItem" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "InventoryItem" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Invoice
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Invoice" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- JournalEntry
ALTER TABLE "JournalEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JournalEntry" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "JournalEntry" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- JournalLine
ALTER TABLE "JournalLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JournalLine" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "JournalLine" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- KitchenStation
ALTER TABLE "KitchenStation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "KitchenStation" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "KitchenStation" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- KitchenTicket
ALTER TABLE "KitchenTicket" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "KitchenTicket" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "KitchenTicket" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Launcher
ALTER TABLE "Launcher" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Launcher" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Launcher" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());
CREATE POLICY shared_catalog_read ON "Launcher" FOR SELECT USING ("organizationId" IS NULL);

-- LedgerAccount
ALTER TABLE "LedgerAccount" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LedgerAccount" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "LedgerAccount" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- LoyaltyReward
ALTER TABLE "LoyaltyReward" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LoyaltyReward" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "LoyaltyReward" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- LoyaltyRule
ALTER TABLE "LoyaltyRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LoyaltyRule" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "LoyaltyRule" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- LoyaltyTransaction
ALTER TABLE "LoyaltyTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LoyaltyTransaction" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "LoyaltyTransaction" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- MaintenanceSession
ALTER TABLE "MaintenanceSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MaintenanceSession" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "MaintenanceSession" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Match
ALTER TABLE "Match" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Match" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Match" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Membership
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Membership" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- MembershipTier
ALTER TABLE "MembershipTier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MembershipTier" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "MembershipTier" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Modifier
ALTER TABLE "Modifier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Modifier" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Modifier" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ModifierGroup
ALTER TABLE "ModifierGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModifierGroup" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ModifierGroup" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Notification
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Notification" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- NotificationTemplate
ALTER TABLE "NotificationTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationTemplate" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "NotificationTemplate" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());
CREATE POLICY shared_catalog_read ON "NotificationTemplate" FOR SELECT USING ("organizationId" IS NULL);

-- Order
ALTER TABLE "Order" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Order" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Order" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- OrderItem
ALTER TABLE "OrderItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrderItem" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "OrderItem" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Organization
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Organization" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Organization" USING ("id" = app.current_org_id());

-- OrganizationFeature
ALTER TABLE "OrganizationFeature" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrganizationFeature" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "OrganizationFeature" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- OrgGameSetting
ALTER TABLE "OrgGameSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OrgGameSetting" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "OrgGameSetting" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- OutboxEvent
ALTER TABLE "OutboxEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OutboxEvent" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "OutboxEvent" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Payment
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Payment" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PaymentGatewayConfig
ALTER TABLE "PaymentGatewayConfig" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentGatewayConfig" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PaymentGatewayConfig" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PeripheralProfile
ALTER TABLE "PeripheralProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PeripheralProfile" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PeripheralProfile" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PricingPackage
ALTER TABLE "PricingPackage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PricingPackage" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PricingPackage" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PricingPlan
ALTER TABLE "PricingPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PricingPlan" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PricingPlan" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PrintJob
ALTER TABLE "PrintJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PrintJob" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PrintJob" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Product
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Product" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ProductBranchPrice
ALTER TABLE "ProductBranchPrice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductBranchPrice" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ProductBranchPrice" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ProductCategory
ALTER TABLE "ProductCategory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductCategory" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ProductCategory" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ProductModifierGroup
ALTER TABLE "ProductModifierGroup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ProductModifierGroup" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ProductModifierGroup" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PromoCode
ALTER TABLE "PromoCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromoCode" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PromoCode" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Promotion
ALTER TABLE "Promotion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Promotion" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Promotion" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PromotionRedemption
ALTER TABLE "PromotionRedemption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromotionRedemption" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PromotionRedemption" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PurchaseOrder
ALTER TABLE "PurchaseOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseOrder" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PurchaseOrder" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PurchaseOrderLine
ALTER TABLE "PurchaseOrderLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseOrderLine" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PurchaseOrderLine" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- PushSubscription
ALTER TABLE "PushSubscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PushSubscription" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "PushSubscription" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- RecipeLine
ALTER TABLE "RecipeLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecipeLine" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "RecipeLine" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Refund
ALTER TABLE "Refund" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Refund" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Refund" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- RemoteSupportSession
ALTER TABLE "RemoteSupportSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RemoteSupportSession" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "RemoteSupportSession" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- RestaurantTable
ALTER TABLE "RestaurantTable" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RestaurantTable" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "RestaurantTable" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Role
ALTER TABLE "Role" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Role" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Role" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());
CREATE POLICY shared_catalog_read ON "Role" FOR SELECT USING ("organizationId" IS NULL);

-- SessionExtension
ALTER TABLE "SessionExtension" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SessionExtension" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "SessionExtension" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- SessionTransfer
ALTER TABLE "SessionTransfer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SessionTransfer" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "SessionTransfer" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- ShellApp
ALTER TABLE "ShellApp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShellApp" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "ShellApp" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());
CREATE POLICY shared_catalog_read ON "ShellApp" FOR SELECT USING ("organizationId" IS NULL);

-- Shift
ALTER TABLE "Shift" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Shift" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Shift" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- StockLevel
ALTER TABLE "StockLevel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockLevel" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "StockLevel" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- StockLot
ALTER TABLE "StockLot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockLot" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "StockLot" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- StockMovement
ALTER TABLE "StockMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockMovement" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "StockMovement" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Subscription
ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscription" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Subscription" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- SubscriptionInvoice
ALTER TABLE "SubscriptionInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SubscriptionInvoice" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "SubscriptionInvoice" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Supplier
ALTER TABLE "Supplier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Supplier" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Supplier" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- SupplierInvoice
ALTER TABLE "SupplierInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupplierInvoice" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "SupplierInvoice" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- SupportTicket
ALTER TABLE "SupportTicket" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupportTicket" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "SupportTicket" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- SyncBatch
ALTER TABLE "SyncBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SyncBatch" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "SyncBatch" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- TaxProfile
ALTER TABLE "TaxProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaxProfile" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "TaxProfile" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- TaxRate
ALTER TABLE "TaxRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaxRate" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "TaxRate" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Team
ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Team" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Team" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Tournament
ALTER TABLE "Tournament" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tournament" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Tournament" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- TournamentPlayer
ALTER TABLE "TournamentPlayer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TournamentPlayer" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "TournamentPlayer" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Wallet
ALTER TABLE "Wallet" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Wallet" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Wallet" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- WalletTransaction
ALTER TABLE "WalletTransaction" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WalletTransaction" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "WalletTransaction" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Warehouse
ALTER TABLE "Warehouse" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Warehouse" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Warehouse" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- WebhookEndpoint
ALTER TABLE "WebhookEndpoint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEndpoint" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "WebhookEndpoint" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- Zone
ALTER TABLE "Zone" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Zone" FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON "Zone" USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());

-- RolePermission (no organizationId: scoped through its Role)
ALTER TABLE "RolePermission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RolePermission" FORCE ROW LEVEL SECURITY;
CREATE POLICY via_role_read ON "RolePermission" FOR SELECT
  USING (EXISTS (SELECT 1 FROM "Role" r WHERE r."id" = "RolePermission"."roleId"));
CREATE POLICY via_role_write ON "RolePermission"
  USING (EXISTS (SELECT 1 FROM "Role" r WHERE r."id" = "RolePermission"."roleId" AND r."organizationId" = app.current_org_id()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Role" r WHERE r."id" = "RolePermission"."roleId" AND r."organizationId" = app.current_org_id()));

