#!/usr/bin/env node
// Generates Row-Level Security SQL for tenant tables.
//
//   node scripts/gen-rls.mjs              → full 0002_rls migration to stdout
//   node scripts/gen-rls.mjs Foo Bar      → policies for new tables Foo, Bar only
//                                           (paste into the migration that creates them)
//
// test/tenancy.static.test.ts fails CI if any tenant table lacks a policy.
import { parseModels, tenantModels, RLS_EXEMPT } from "./schema-meta.mjs";

/** Tables whose rows with organizationId = NULL are a shared platform catalog. */
export const SHARED_CATALOG = new Set(["Launcher", "Game", "ShellApp", "NotificationTemplate", "Role"]);

/** Tenant tables the runtime role may read but never write (platform-managed). */
export const TENANT_READ_ONLY = ["Subscription", "SubscriptionInvoice", "OrganizationFeature", "ImpersonationSession"];

const q = (ident) => `"${ident}"`;

export function policySql({ name, orgOptional, isRoot }) {
  const t = q(name);
  const lines = [`-- ${name}`, `ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;`, `ALTER TABLE ${t} FORCE ROW LEVEL SECURITY;`];
  if (isRoot) {
    lines.push(`CREATE POLICY tenant_isolation ON ${t} USING ("id" = app.current_org_id());`);
  } else if (SHARED_CATALOG.has(name)) {
    lines.push(
      `CREATE POLICY tenant_isolation ON ${t} USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());`,
      `CREATE POLICY shared_catalog_read ON ${t} FOR SELECT USING ("organizationId" IS NULL);`,
    );
  } else {
    // Also used for nullable org columns (e.g. AuditLog): NULL-org rows are
    // platform rows and are invisible to tenants.
    void orgOptional;
    lines.push(
      `CREATE POLICY tenant_isolation ON ${t} USING ("organizationId" = app.current_org_id()) WITH CHECK ("organizationId" = app.current_org_id());`,
    );
  }
  return lines.join("\n");
}

export function fullMigration() {
  const tables = tenantModels(parseModels()).filter((t) => !(t.name in RLS_EXEMPT));
  const header = `-- ─────────────────────────────────────────────────────────────────────────────
-- 0002_rls — tenant isolation via Postgres Row-Level Security
-- GENERATED by packages/db/scripts/gen-rls.mjs — do not edit by hand.
--
-- Runtime connections use a login role that is a member of arena_app
-- (NOBYPASSRLS). Every request runs inside a transaction that first executes
--   SELECT set_config('app.current_org', '<org uuid>', true);
-- If the setting is missing, app.current_org_id() is NULL and every policy
-- evaluates to NULL → zero rows. The system fails CLOSED.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE SCHEMA IF NOT EXISTS app;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_app') THEN
    CREATE ROLE arena_app NOLOGIN NOBYPASSRLS;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_readonly') THEN
    CREATE ROLE arena_readonly NOLOGIN NOBYPASSRLS;
  END IF;
  -- Group role for platform (Super Admin) services. NOTE: BYPASSRLS is not
  -- inherited through membership; the platform *login* role must itself be
  -- created WITH BYPASSRLS by infrastructure (see docs/05-multi-tenancy.md).
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'arena_platform') THEN
    CREATE ROLE arena_platform NOLOGIN;
  END IF;
END
$$;

CREATE OR REPLACE FUNCTION app.current_org_id() RETURNS uuid
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $fn$ SELECT NULLIF(current_setting('app.current_org', true), '')::uuid $fn$;

GRANT USAGE ON SCHEMA public, app TO arena_app, arena_readonly, arena_platform;
GRANT EXECUTE ON FUNCTION app.current_org_id() TO arena_app, arena_readonly, arena_platform;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO arena_app, arena_platform;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO arena_readonly;
REVOKE ALL ON "_prisma_migrations" FROM arena_app, arena_readonly;
-- Tables created by later migrations (run as the owner) get the same grants.
-- They still need their own RLS policy: the static tenancy test enforces it.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO arena_app, arena_platform;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO arena_readonly;

-- Platform reference data & catalogs: tenants read, never write.
REVOKE INSERT, UPDATE, DELETE ON "Country", "Currency", "SubscriptionPlan", "PlanFeature",
  "ClientRelease", "Permission", "PlatformRoleAssignment" FROM arena_app;
-- Tenant rows managed by the platform (billing, feature flags, impersonation).
REVOKE INSERT, UPDATE, DELETE ON ${TENANT_READ_ONLY.map(q).join(", ")} FROM arena_app;
-- Tenants never create or delete organizations.
REVOKE INSERT, DELETE ON "Organization" FROM arena_app;
`;

  const rolePermission = `-- RolePermission (no organizationId: scoped through its Role)
ALTER TABLE "RolePermission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RolePermission" FORCE ROW LEVEL SECURITY;
CREATE POLICY via_role_read ON "RolePermission" FOR SELECT
  USING (EXISTS (SELECT 1 FROM "Role" r WHERE r."id" = "RolePermission"."roleId"));
CREATE POLICY via_role_write ON "RolePermission"
  USING (EXISTS (SELECT 1 FROM "Role" r WHERE r."id" = "RolePermission"."roleId" AND r."organizationId" = app.current_org_id()))
  WITH CHECK (EXISTS (SELECT 1 FROM "Role" r WHERE r."id" = "RolePermission"."roleId" AND r."organizationId" = app.current_org_id()));`;

  return [header, ...tables.map(policySql), rolePermission, ""].join("\n\n");
}

if (import.meta.url === `file://${process.argv[1].replace(/\\/g, "/")}` || process.argv[1]?.endsWith("gen-rls.mjs")) {
  const only = process.argv.slice(2);
  if (only.length) {
    const all = new Map(tenantModels(parseModels()).map((t) => [t.name, t]));
    for (const name of only) {
      const t = all.get(name);
      if (!t) throw new Error(`${name} is not a tenant model (no organizationId)`);
      process.stdout.write(policySql(t) + "\n\n");
    }
  } else {
    process.stdout.write(fullMigration());
  }
}
