// Generates dev secrets into the repo-root .env (only the ones that are missing).
//   npm run keys -w @arena/api
// Production keys come from the secret manager, never from this script.
import { generateKeyPairSync, randomBytes } from "node:crypto";
import { existsSync, readFileSync, appendFileSync } from "node:fs";
import { resolve } from "node:path";
import webpush from "web-push";

const envPath = resolve(import.meta.dirname, "../../../.env");
const current = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
const has = (k: string) => new RegExp(`^${k}=`, "m").test(current);

const lines: string[] = [];
if (!has("JWT_PRIVATE_KEY_B64") || !has("JWT_PUBLIC_KEY_B64")) {
  const { privateKey, publicKey } = generateKeyPairSync("ed25519", {
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
    publicKeyEncoding: { type: "spki", format: "pem" },
  });
  lines.push(`JWT_PRIVATE_KEY_B64=${Buffer.from(privateKey).toString("base64")}`);
  lines.push(`JWT_PUBLIC_KEY_B64=${Buffer.from(publicKey).toString("base64")}`);
}
if (!has("MFA_ENCRYPTION_KEY_B64")) lines.push(`MFA_ENCRYPTION_KEY_B64=${randomBytes(32).toString("base64")}`);
if (!has("COMMAND_KEK_B64")) lines.push(`COMMAND_KEK_B64=${randomBytes(32).toString("base64")}`);
if (!has("VAPID_PUBLIC_KEY") || !has("VAPID_PRIVATE_KEY")) {
  const v = webpush.generateVAPIDKeys();
  lines.push(`VAPID_PUBLIC_KEY=${v.publicKey}`, `VAPID_PRIVATE_KEY=${v.privateKey}`);
}

if (lines.length) {
  appendFileSync(envPath, `${current.endsWith("\n") || !current ? "" : "\n"}\n# API secrets (dev) — generated by apps/api/scripts/gen-keys.ts\n${lines.join("\n")}\n`);
  console.log(`Added ${lines.length} secret(s) to ${envPath}`);
} else {
  console.log("All API secrets already present in .env");
}
